version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:16.9.0-ce.0
    container_name: gitlab
    restart: always
    hostname: '10.1.0.37'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '49153:80'
      - '49154:443'
      - '49155:23'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'